### ISSUE TITLE
Needs deployed

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/codeforfocoissues#1]
In order for us to use this we will need to deploy it to Heroku.

**Comment by abettermap** [comment]
Cool, glad we are still pursuing this instead of the Google form.

What is the next step?

**Comment by JordanMajd** [comment]
My best guess at what needs to be done

1. Create an account called CFFCBot or something, using a cffc email address.
1. Login to the CFFC heroku account and deploy.
1. Use the bots creds as environment variables.

I'm not sure if this tool hard codes the credentials or uses env vars. So that might mean a line of code needs tweakes.

Looks like I need to figure out sharing credentials for heroku and admin email securely so that people can do stuff like this in the future without me.
